mindmap
  root((Validacao e Erros))
    Fundamentos
      Validacao como Contrato
      Fail Fast
      Erros como Dados
      Camadas de Erro
    Aplicacao Express
      Validacao Manual
      AppError class
      Middleware Centralizado
        Switch status
        SyntaxError 400
        Inesperado 500
      try catch next err
      Projeto POST tarefas
    Bibliotecas
      joi
      zod
