mindmap
  root((Code Smells))
    Bloaters
      Long Method
      Large Class
      Long Parameter List
      Data Clumps
    Abusers
      Switch Statements
      Temporary Field
      Alternative Classes
    Dispensables
      Comments
      Duplicate Code
      Dead Code
      Lazy Class
    Change Preventers
      Divergent Change
      Shotgun Surgery
      Feature Envy