flowchart TD
    U[Usuario] --> P[Preferencias pessoais<br/>Resposta em portugues<br/>Indentacao preferida]
    R[Repositorio] --> T[Convencoes do time<br/>Stack do projeto<br/>Estilo do time<br/>Restricoes]
    O[Organizacao] --> C[Politicas corporativas<br/>Seguranca<br/>Compliance]