mindmap
  root((Eventos e Ciclo de Vida))
    FUNDAMENTOS
      Modelo de Eventos
        Campainha
        Emissor e Ouvinte
        Callback
    addEventListener
      Sintaxe
      Tipos de Evento
        Mouse click dblclick
        Teclado keydown keyup
        Formulario submit change input
      removeEventListener
    Objeto event
      target
      key
      preventDefault
    Propagacao
      Captura descida
      Target
      Bubbling subida
      stopPropagation
    Delegacao
      Listener no pai
      event target identifica filho
      matches e closest
    Ciclo de Vida do CE
      connectedCallback adicionar listener
      disconnectedCallback remover listener
      observedAttributes
      attributeChangedCallback reagir
    Projeto
      e-tarefa interativo
      Checkbox com click
      Reatividade com atributo