mindmap
  root((Prototypes e Heranca Prototipal))
    Heranca Universal
      DNA e Caracteristicas
      Sobrenome da Familia
      Delegacao Natural
      Heranca ao Vivo vs Copia
    Prototype Chain
      Todo Objeto Tem Prototipo
      Object create
      proto vs getPrototypeOf
      Cadeia de Busca
    Propriedades
      Proprias vs Herdadas
      hasOwn
      for in vs Object keys
    Built-in Prototypes
      Array prototype
      String prototype
      Function prototype
