mindmap
  root((Promises Fetch e Async Await))
    FUNDAMENTOS PARTE 1
      Problema do Tempo
      Promessa como Contrato
      Tres Estados
        Pendente
        Cumprida
        Rejeitada
      Encadeamento
      Composicao
        Promise all
        Promise race
        Promise allSettled
    APLICACAO PARTE 2
      Criar Promise
      then catch finally
      Fetch GET
      Fetch POST
      AbortController
      Async Await
      Try Catch
      Projeto Frases
