mindmap
  root((Web APIs do Navegador))
    Console API
      console log
      console table
    Window API
      alert
      prompt
    Document API
      document
      getElementById
      querySelector
