mindmap
  root((DOM e Custom Elements))
    Arvore de Nos
      document como raiz
      parentElement
      children
      nextElementSibling
    Seletores
      getElementById
      querySelector
      querySelectorAll
    Manipulacao
      textContent
      innerHTML
      classList
    Custom Elements
      extends HTMLElement
      customElements define
      connectedCallback
      e-tarefa
