mindmap
  root((Servidor HTTP Node.js))
    Cliente e Servidor
      HTTP
      TCP
      Porta
      URL
    Módulo http
      createServer
      req e res
      server listen
    Roteamento
      URL path
      Método HTTP
      if else
    Query String
      URL API
      searchParams
    Body Parsing
      EventEmitter
      req on data
      req on end
    Projeto Tarefas
      GET tarefas
      POST tarefas
      tarefas repo
