mindmap
  root((Funcoes Avancadas))
    FUNDAMENTOS
      Delegar Trabalho
        Callback: passe uma funcao
        HOF: receba ou retorne funcao
        Funcao como valor
      Transformar Colecoes
        Imutabilidade: copie nao altere
        Mapear: cada item vira outro
        Filtrar: selecione itens
        Acumular: junte em um valor
    APLICACAO JavaScript
      Arrow Functions
        Sintaxe completa
        Parenteses opcionais
        Retorno implicito vs explicito
      Callbacks e HOFs
        Funcao em variavel
        Callback sincrono
        HOF que retorna funcao
      Metodos de Array
        forEach: iterar
        map: transformar
        filter: selecionar
        reduce: acumular
        find: buscar
        some: existe algum
        every: todos passam
      Method Chaining
        Pipeline de transformacao
        filter map forEach