mindmap
  root((Classes em JavaScript))
    FUNDAMENTOS
      O que e uma classe
        Molde e fabrica
        Blueprint e instancia
        Analogia forma de bolo
      Por que classes existem
        Problema da repeticao
        Consistencia garantida
        Manutencao centralizada
    APLICACAO JavaScript
      Sintaxe class
        constructor
        Metodos
        new
      Heranca extends super
        Classe filha
        super e this
        Sobrescrita de metodos
      Campos privados
        hash privado
        Diferenca do underscore
      Metodos estaticos static
        Pertencem a classe
        Nao a instancia
      Getters e Setters
        Acesso controlado
        Validacao
        Propriedades calculadas
    Revelacao
      Acucar sintatico
      class equals prototype
      Conexao Aula 15
