flowchart LR
    C[class FormaBolo] --> I1[Instancia 1: bolo de brigadeiro]
    C --> I2[Instancia 2: bolo de chantilly]
    C --> I3[Instancia 3: bolo de granulado]
    C --> I4[Instancia 4: bolo de coco]
    C --> I5[Instancia 5: bolo de cenoura]
